---
title: "Linear Regression"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```


```{r}
### Content ### ggplot | ddply | apa-Outputs | Inequality detection

# 13  Packages & Working Directory
# 24  Recoding Variables & Regression
# 42  Introduction to GGplot
# 57  Interaction Plotting in ggplot: Gender Wage-Gap
# 80  GAM (Generalized additive models with integrated smoothness estimation)
# 100 ddply & Data Management
# 116 Descriptive Statistics export in apa-Style
# 147 Inequality Detection: Plotting the Lorenz-Curve & ineq. gap


library(car) #Recode-Operations
library(ggplot2) #Graphical Design
library(mgcv) # GAM (Generalized additive models with integrated smoothness estimation)
library(readstata13)

# If your project-surrounding doesn't work, use setwd manually


SOEP2 <- read.dta13(file="data/offline/soep/new8.dta" , convert.factors=F)

# Recoding 
SOEP2$alter = 2003 - SOEP2$gebjahr
SOEP2$alter [SOEP2$alter == 2004] <- NA # erase nas
SOEP2$netinc = recode(SOEP2$tp7602,"-3=NA;-2=NA;-1=NA")

# Multivariate Regression Sex & Age
mod1=lm(netinc~sex+alter, data=SOEP2)
summary(mod1)



# A deeper look at income

ggplot(data=SOEP2,aes(x=netinc)) + 
  geom_density()+
  xlim(0,10000)+
  theme_bw()

# Ggplot Darstellung

ggplot(data=SOEP2, #dataset
       aes(x=alter,y=netinc))+  #aestetics
  geom_point(size=1)+    # what you want to be plotted
  xlim(18,100) +   # readjust xlim
  ylim(0,13000) +  # dump the superrich
  ggtitle("GGplot-Regression") +
  xlab ("Alter")+
  ylab ("Net_Income") + 
  theme_bw()+ # makes it nice and black-and-white
  stat_smooth(method = "lm", formula = y~x, color="green")



# Applied Feminism: Is there a gender effect?

SOEP2$sex.factor <- factor(SOEP2$sex , levels = c(2,1), labels= c("weiblich","männlich"))


mod2=lm(netinc~sex.factor*alter, data=SOEP2) # Interaction Terms
summary(mod2) # How do you interpret the interaction term?


ggplot(data=SOEP2, #dataset
       aes(x=alter,y=netinc,group=sex.factor))+
  geom_point(size=0.7,aes(color=sex.factor)) +   # what you want to be plotted
  xlim(20,85) +   # readjust xlim
  ylim(0,13000) +  # dump the superrich
  ggtitle("GGplot-Regression") +
  xlab ("Alter")+
  ylab ("Net_Income") + 
  theme_bw() + # makes it nice and black-and-white
  scale_color_discrete() +
  stat_smooth(method = "lm", formula = y~x, aes(color=sex.factor)) 
  


# GAM
# Alternativ Normales lm-Modell letzte Zeile ersetzen durch GAM (Generalized additive models with integrated smoothness estimation)
library(hrbrthemes)
library(extrafont)

gg <- 
  ggplot(data=SOEP2, #dataset
       aes(x=alter,y=netinc,  #aestetics
           group=sex.factor))+
  geom_point(size=0.7,aes(color=sex.factor)) +   # what you want to be plotted
  xlim(20,85) +   # readjust xlim
  ylim(0,13000) +  # dump the superrich
  labs(x = "alter",
        y = "income",
        title = "Titel",
        subtitle = "SUB",
        caption = "lalal")+
  scale_color_discrete()+
  stat_smooth(method = gam, formula= y ~ s(x),aes(color=sex.factor))+
  hrbrthemes::theme_ipsum(grid = "Y")# 

#ggsave(filename = "lala.pdf",plot = gg,device = "pdf",width = 10,height = 6,dpi = 1000)


# Ddply Stuff & Data Management

library(dplyr)
library(plyr)

df <- ddply(.data = SOEP2,
       .variables = c("sex.factor"), # Variablen to be used for splitting
       .fun = summarize,
       INCOME= mean(netinc,na.rm = TRUE),
       SD_INCOME= sd(netinc,na.rm = TRUE),
       AGE = mean(alter,na.rm = TRUE),
       SD_AGE = sd(alter,na.rm = TRUE)
)
df





# advanced R: Inequality detection 

## inequality

library(RODBC)
library(ineq)     # for Lc and Gini
library(dplyr)
library(ggplot2)
library(scales)
library(stringr)  # for str_wrap

lorenz <- Lc(SOEP2$netinc)
lorenz_df <- data.frame(prop_pop = lorenz$p, income = lorenz$L) %>%
  mutate(prop_equality = prop_pop)

 ggplot(lorenz_df, aes(x = prop_pop, y = income)) +
  geom_ribbon(aes(ymax = prop_equality, ymin = income), fill = "yellow") +
  geom_line() +
  geom_abline(slope = 1) +
  scale_x_continuous("nCumulative proportion of population", label = percent) +
  scale_y_continuous("Cumulative proportion of incomen", label = percent) +
  theme_minimal(base_family = "myfont") +
  coord_equal() +
  annotate("text", 0.53, 0.4, label = "Inequalityngap", angle = 45,family = "myfont") +
  annotate("text", 0.5, 0.6, label = "Complete equality line", angle = 45, family = "myfont") + 
  ggtitle (
    str_wrap("Cumulative distribution of SOEC individual income ", 46))

```